export {default as Header} from "./Header/Header"
export {default as SectionMain} from "./SectionMain/SectionMain"
export {default as UmrahPrograms} from "./UmrahPrograms/UmrahPrograms"
export {default as HajjPrograms} from "./HajjPrograms/HajjPrograms"
export {default as Hotel} from "./Hotel/Hotel"
export {default as About} from "./About/About"
